/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ylcq_ffmpeg_FFDecoder */

#ifndef _Included_com_ylcq_ffmpeg_FFDecoder
#define _Included_com_ylcq_ffmpeg_FFDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ylcq_ffmpeg_FFDecoder
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ylcq_ffmpeg_FFDecoder_init
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_ylcq_ffmpeg_FFDecoder
 * Method:    decoding
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ylcq_ffmpeg_FFDecoder_decoding
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ylcq_ffmpeg_FFDecoder
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ylcq_ffmpeg_FFDecoder_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
