/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ylcq_ffmpeg_VidoeUtils */

#ifndef _Included_com_ylcq_ffmpeg_VidoeUtils
#define _Included_com_ylcq_ffmpeg_VidoeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ylcq_ffmpeg_VidoeUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ylcq_ffmpeg_VidoeUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
