/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ylcq_ffmpeg_FFEncoder */

#ifndef _Included_com_ylcq_ffmpeg_FFEncoder
#define _Included_com_ylcq_ffmpeg_FFEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ylcq_ffmpeg_FFEncoder
 * Method:    init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ylcq_ffmpeg_FFEncoder_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ylcq_ffmpeg_FFEncoder
 * Method:    encoding
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ylcq_ffmpeg_FFEncoder_encoding
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ylcq_ffmpeg_FFEncoder
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ylcq_ffmpeg_FFEncoder_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
