/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ylcq_ffmpeg_FFPlayer */

#ifndef _Included_com_ylcq_ffmpeg_FFPlayer
#define _Included_com_ylcq_ffmpeg_FFPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ylcq_ffmpeg_FFPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_ylcq_ffmpeg_FFPlayer_render
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
